### ISSUE TITLE
toDataURL error

### ISSUE THREAD

**Issue by iamvitali** [hoixw/SmartFrameDownloader#1]
When clicking the button "Download Hi-Res" it enlarges the image but doesn't download it and throws an error in the console:

![image](https://github.com/hoixw/SmartFrameDownloader/assets/8069264/9339ae93-0afd-48a1-800b-dc77ad65f0cc)

![image](https://github.com/hoixw/SmartFrameDownloader/assets/8069264/2f618f5c-cc0e-4b46-93a0-cbd184e5bcb2)

**Comment by hoixw** [comment]
Which website was this on?

I will take a look at the issue now, but it _looks_ like SmartFrame updated their DRM from what I'm seeing.

**Comment by hoixw** [comment]
Finally had some time to take a look at it — yes, they had updated their DRM. They now use 'closed shadow DOMs', which are a unique little feature designed to be totally inaccessible to JS code. It took me a while to figure out how to bypass this, especially given I'm trying to break a feature written by someone smarter than me. 

Nonetheless, I have a solution:

The button appears as normal but clicking it results in a refresh, and on refresh, the shadow DOM code is hijacked, resulting in every shadow DOM being 'open'. They can't be accessed normally (so the code needed a little updating), but they *can* be accessed, so it now works :D. 

I've tested it on the sample websites in the readme — coventry.digital and the Historic England archive. Let me know if it works for you on whatever site you were using, and if it does, I will close the issue.
