### ISSUE TITLE
The code not work

### ISSUE THREAD

**Issue by danielyepezgarces** [hoixw/SmartFrameDownloader#2]
It's been so long that the code is already obsolete.

**Comment by hoixw** [comment]
Can you add more detail? Like which website, what is the error, etc.

**Comment by danielyepezgarces** [comment]
https://historicengland.org.uk/images-books/photos/item/AA50/00456

For example, this URL is not detected by the script in Canva, nor does any
button appear.

**Comment by hoixw** [comment]
It doesn't work, but it's not a significant issue. All that happened was the element it detects (`smart-frame`) was changed to `smartframe-embed`. Once you change the element names it works—I tested it on the link you provided and a few other sites.

I will push the fix and close the issue.
