### ISSUE TITLE
Doesn't seem to work on Tate-Images.com

### ISSUE THREAD

**Issue by thejra** [hoixw/SmartFrameDownloader#3]
I get the purple icon on ViolentMonkey but no option to download.

<img width="368" alt="image" src="https://github.com/user-attachments/assets/02399ab2-edf3-4949-9f62-5e3d8a836893">

**Comment by hoixw** [comment]
If it detects a SmartFrame the button will show, and from what I can tell, the button is showing on the pages where there are SmartFrames.

Keep in mind downloading these images is probably illegal. See the Copyright, Designs and Patents Act 1988.
